import psycopg2
from flask import jsonify

# The file for creating DB with 2 tables (planetsData, moonsData)

conn = psycopg2.connect(
        host="localhost",
        database="solarsystem",
        user="postgres",
        password="0000")

# Open a cursor to perform database operations
cur = conn.cursor()

planetsData = [
    { 'name': "Sun", 'size': 15, 'position': 0, 'rotationSpeed': 0.004, 'orbitSpeed': 0, 'moons': 0, 
     'description': "Fiery star", 'history': "Central to our solar system",
     'sizeOriginal': 1391000, 'positionOriginal': 0, 'rotationSpeedOriginal': 25.38, 'orbitSpeedOriginal': 0 },
   
    { 'name': "Mercury", 'size': 3.2, 'position': 28, 'rotationSpeed': 0.004, 'orbitSpeed': 0.04, 'moons': 0, 
     'description': "Swift messenger", 'history': "Named after Roman god of commerce",
     'sizeOriginal': 4879, 'positionOriginal': 57.9, 'rotationSpeedOriginal': 58.65, 'orbitSpeedOriginal': 47.87 },
   
    { 'name': "Venus", 'size': 5.8, 'position': 44, 'rotationSpeed': 0.002, 'orbitSpeed': 0.015, 'moons': 0, 
     'description': "Shrouded beauty", 'history': "Named after Roman goddess of love",
     'sizeOriginal': 12104, 'positionOriginal': 108.2, 'rotationSpeedOriginal': 243.02, 'orbitSpeedOriginal': 35.02 },
   
    { 'name': "Earth", 'size': 6, 'position': 62, 'rotationSpeed': 0.02, 'orbitSpeed': 0.01, 'moons': 1, 
     'description': "Blue oasis", 'history': "The cradle of humanity",
     'sizeOriginal': 12742, 'positionOriginal': 149.6, 'rotationSpeedOriginal': 0.997, 'orbitSpeedOriginal': 29.78 },
    
    { 'name': "Mars", 'size': 4, 'position': 78, 'rotationSpeed': 0.018, 'orbitSpeed': 0.008, 'moons': 2, 
     'description': "Red planet", 'history': "Explored for signs of life",
     'sizeOriginal': 6779, 'positionOriginal': 227.9, 'rotationSpeedOriginal': 1.026, 'orbitSpeedOriginal': 24.077 },
   
    { 'name': "Jupiter", 'size': 12, 'position': 100, 'rotationSpeed': 0.04, 'orbitSpeed': 0.002, 'moons': 95, 
     'description': "Giant storm", 'history': "Largest planet with iconic bands",
     'sizeOriginal': 139822, 'positionOriginal': 778.3, 'rotationSpeedOriginal': 0.41354, 'orbitSpeedOriginal': 13.07 },
  
    { 'name': "Saturn", 'size': 10, 'position': 138, 'rotationSpeed': 0.038, 'orbitSpeed': 0.0009, 'moons': 146, 
     'innerRadius': 10, 'outerRadius': 20, 'description': "Ringed wonder", 'history': "Famous for its stunning rings",
     'sizeOriginal': 116464, 'positionOriginal': 1426.9, 'rotationSpeedOriginal': 0.44401, 'orbitSpeedOriginal': 9.69 },
   
    { 'name': "Uranus", 'size': 7, 'position': 176, 'rotationSpeed': 0.032, 'orbitSpeed': 0.0004, 'moons': 27,
     'innerRadius': 7, 'outerRadius': 12, 'description': "Tilted ice giant", 'history': "Discovered by William Herschel in 1781",
     'sizeOriginal': 50724, 'positionOriginal': 2870.9, 'rotationSpeedOriginal': 0.71833, 'orbitSpeedOriginal': 6.81 },
   
    { 'name': "Neptune", 'size': 7, 'position': 200, 'rotationSpeed': 0.032, 'orbitSpeed': 0.0001, 'moons': 14, 
     'description': "Mystic blue", 'history': "First predicted by mathematical calculations",
     'sizeOriginal': 49244, 'positionOriginal': 4495.1, 'rotationSpeedOriginal': 0.67125, 'orbitSpeedOriginal': 5.43 }
]


moonsData = [  

    # Earth moon
    {'name': "Moon", 'extendsPlanet': "Earth", 'size': 3, 'position': 10, 'rotationSpeed': 0.038, 'orbitSpeed': 0.01, 'id_planet': 4, 'sizeOriginal': 3474.8, 'positionOriginal': 384400, 'rotationSpeedOriginal': 27, 'orbitSpeedOriginal': 1.022,
     'description': "The Moon is Earth's only natural satellite.", 'history': "It has been a source of fascination and inspiration for humanity throughout history."},
   
    # Mars' moons
    { "name": "Phobos", "extendsPlanet": "Mars", "size": 3.5, "position": 10, "rotationSpeed": 0.015, "orbitSpeed": 0.004, "id_planet": 5, "sizeOriginal": 22.2, "positionOriginal": 9378, "rotationSpeedOriginal": 0.318, "orbitSpeedOriginal": 4.68,
      "description": "Phobos is the larger and innermost moon of Mars.", "history": "It was discovered by Asaph Hall in 1877." },
    { "name": "Deimos", "extendsPlanet": "Mars", "size": 2.5, "position": 14, "rotationSpeed": 0.02, "orbitSpeed": 0.012, "id_planet": 5, "sizeOriginal": 12.4, "positionOriginal": 23460, "rotationSpeedOriginal": 1.262, "orbitSpeedOriginal": 2.88,
      "description": "Deimos is the smaller and outermost moon of Mars.", "history": "It was discovered by Asaph Hall in 1877." },

    # Jupiter's moons
    { "name": "Amaltea", "extendsPlanet": "Jupiter", "size": 0.4, "position": 13, "rotationSpeed": 0.025, "orbitSpeed": 0.009, "id_planet": 6, "sizeOriginal": 168, "positionOriginal": 181400, "rotationSpeedOriginal": 0.498, "orbitSpeedOriginal": 7.2,
      "description": "Amaltea is a small irregular-shaped moon of Jupiter.", "history": "It was discovered by Edward Emerson Barnard in 1892." },
    { "name": "Io", "extendsPlanet": "Jupiter", "size": 1.2, "position": 19, "rotationSpeed": 0.035, "orbitSpeed": 0.008, "id_planet": 6, "sizeOriginal": 3643.2, "positionOriginal": 421700, "rotationSpeedOriginal": 1.769, "orbitSpeedOriginal": 5.6,
      "description": "Io is known for its volcanic activity and colorful surface.", "history": "It was discovered by Galileo Galilei in 1610." },
    { "name": "Europa", "extendsPlanet": "Jupiter", "size": 2.3, "position": 26, "rotationSpeed": 0.032, "orbitSpeed": 0.007, "id_planet": 6, "sizeOriginal": 3121.6, "positionOriginal": 671100, "rotationSpeedOriginal": 3.551, "orbitSpeedOriginal": 17.28,
      "description": "Europa is one of Jupiter's Galilean moons known for its icy surface.", "history": "Its potential subsurface ocean makes it a target for astrobiology." },
    { "name": "Ganymede", "extendsPlanet": "Jupiter", "size": 3.8, "position": 36, "rotationSpeed": 0.022, "orbitSpeed": 0.005, "id_planet": 6, "sizeOriginal": 5262.4, "positionOriginal": 1070400, "rotationSpeedOriginal": 7.154, "orbitSpeedOriginal": 18,
      "description": "Ganymede is the largest moon in the solar system and has its own magnetic field.", "history": "It was discovered by Galileo Galilei in 1610." },
    { "name": "Callisto", "extendsPlanet": "Jupiter", "size": 2.7, "position": 46, "rotationSpeed": 0.028, "orbitSpeed": 0.006, "id_planet": 6, "sizeOriginal": 4820.6, "positionOriginal": 1882700, "rotationSpeedOriginal": 16.689, "orbitSpeedOriginal": 20.16,
      "description": "Callisto is another of Jupiter's Galilean moons and has a heavily cratered surface.", "history": "It was discovered along with the other Galilean moons by Galileo Galilei in 1610." },
    { "name": "Amaltea", "extendsPlanet": "Jupiter", "size": 0.4, "position": 50, "rotationSpeed": 0.025, "orbitSpeed": 0.009, "id_planet": 6, "sizeOriginal": 168, "positionOriginal": 181400, "rotationSpeedOriginal": 0.498, "orbitSpeedOriginal": 7.2, "description": "Amaltea is a small irregular-shaped moon of Jupiter.", "history": "It was discovered by Edward Emerson Barnard in 1892." },
    { "name": "Himalia", "extendsPlanet": "Jupiter", "size": 4.5, "position": 56, "rotationSpeed": 0.296, "orbitSpeed": 0.43, "id_planet": 6, "sizeOriginal": 170, "positionOriginal": 11480000, "rotationSpeedOriginal": 0.296, "orbitSpeedOriginal": 0.43, "description": "Himalia is irregularly shaped and one of Jupiter's outer moons.", "history": "It was discovered by Charles Dillon Perrine in 1904." },
    { "name": "Elara", "extendsPlanet": "Jupiter", "size": 3.2, "position": 64, "rotationSpeed": 0.498, "orbitSpeed": 0.42, "id_planet": 6, "sizeOriginal": 86, "positionOriginal": 11740000, "rotationSpeedOriginal": 0.498, "orbitSpeedOriginal": 0.42, "description": "Elara is another irregular moon of Jupiter.", "history": "It was discovered by Charles Dillon Perrine in 1905." },
    { "name": "Pasiphae", "extendsPlanet": "Jupiter", "size": 2.8, "position": 73, "rotationSpeed": 0.274, "orbitSpeed": 0.69, "id_planet": 6, "sizeOriginal": 30, "positionOriginal": 22600000, "rotationSpeedOriginal": 0.274, "orbitSpeedOriginal": 0.69, "description": "Pasiphae is a retrograde irregular moon of Jupiter.", "history": "It was discovered by Philibert Jacques Melotte in 1908." },
    { "name": "Sinope", "extendsPlanet": "Jupiter", "size": 5.7, "position": 81, "rotationSpeed": 0.242, "orbitSpeed": 0.74, "id_planet": 6, "sizeOriginal": 38, "positionOriginal": 23700000, "rotationSpeedOriginal": 0.242, "orbitSpeedOriginal": 0.74, "description": "Sinope is a distant irregular moon of Jupiter.", "history": "It was discovered by Seth Barnes Nicholson in 1914." },
    { "name": "Lysithea", "extendsPlanet": "Jupiter", "size": 4.8, "position": 89, "rotationSpeed": 0.259, "orbitSpeed": 0.64, "id_planet": 6, "sizeOriginal": 36, "positionOriginal": 24170000, "rotationSpeedOriginal": 0.259, "orbitSpeedOriginal": 0.64, "description": "Lysithea is another irregular moon of Jupiter.", "history": "It was discovered by Seth Barnes Nicholson in 1938." },
    { "name": "Ananke", "extendsPlanet": "Jupiter", "size": 2.5, "position": 64, "rotationSpeed": 0.358, "orbitSpeed": 0.36, "id_planet": 6, "sizeOriginal": 28, "positionOriginal": 7500000, "rotationSpeedOriginal": 0.358, "orbitSpeedOriginal": 0.36, "description": "Ananke is a prograde irregular moon of Jupiter.", "history": "It was discovered by Seth Barnes Nicholson in 1951." },
    { "name": "Carme", "extendsPlanet": "Jupiter", "size": 4.1, "position": 72, "rotationSpeed": 0.361, "orbitSpeed": 0.25, "id_planet": 6, "sizeOriginal": 46, "positionOriginal": 16415000, "rotationSpeedOriginal": 0.361, "orbitSpeedOriginal": 0.25, "description": "Carme is an irregular moon of Jupiter.", "history": "It was discovered by Seth Barnes Nicholson in 1938." },
    { "name": "Iocaste", "extendsPlanet": "Jupiter", "size": 3.6, "position": 78, "rotationSpeed": 0.329, "orbitSpeed": 0.27, "id_planet": 6, "sizeOriginal": 34, "positionOriginal": 20400000, "rotationSpeedOriginal": 0.329, "orbitSpeedOriginal": 0.27, "description": "Iocaste is a prograde irregular moon of Jupiter.", "history": "It was discovered by Seth Barnes Nicholson in 2000." },
    { "name": "Praxidike", "extendsPlanet": "Jupiter", "size": 3.7, "position": 82, "rotationSpeed": 0.32, "orbitSpeed": 0.23, "id_planet": 6, "sizeOriginal": 36, "positionOriginal": 20906000, "rotationSpeedOriginal": 0.32, "orbitSpeedOriginal": 0.23, "description": "Praxidike is a prograde irregular moon of Jupiter.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Yanga R. Fernández, and Eugene A. Magnier in 2000." },
    { "name": "Harpalyke", "extendsPlanet": "Jupiter", "size": 2.9, "position": 89, "rotationSpeed": 0.374, "orbitSpeed": 0.45, "id_planet": 6, "sizeOriginal": 30, "positionOriginal": 23579430, "rotationSpeedOriginal": 0.374, "orbitSpeedOriginal": 0.45, "description": "Harpalyke is a retrograde irregular moon of Jupiter.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Yanga R. Fernández, and Eugene A. Magnier in 2000."},
    { "name": "Mneme", "extendsPlanet": "Jupiter", "size": 2.8, "position": 90, "rotationSpeed": 0.397, "orbitSpeed": 0.47, "id_planet": 6, "sizeOriginal": 28, "positionOriginal": 20673250, "rotationSpeedOriginal": 0.397, "orbitSpeedOriginal": 0.47, "description": "Mneme is a retrograde irregular moon of Jupiter.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Yanga R. Fernández, and Eugene A. Magnier in 2000."},
    { "name": "Thelxinoe", "extendsPlanet": "Jupiter", "size": 2.4, "position": 92, "rotationSpeed": 0.454, "orbitSpeed": 0.48, "id_planet": 6, "sizeOriginal": 24, "positionOriginal": 18217600, "rotationSpeedOriginal": 0.454, "orbitSpeedOriginal": 0.48, "description": "Thelxinoe is a retrograde irregular moon of Jupiter.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Yanga R. Fernández, and Eugene A. Magnier in 2000."},
    {"name": "Helike", "extendsPlanet": "Jupiter", "size": 3.2, "position": 95, "rotationSpeed": 0.330, "orbitSpeed": 0.49, "id_planet": 6, "sizeOriginal": 36, "positionOriginal": 23584960, "rotationSpeedOriginal": 0.330, "orbitSpeedOriginal": 0.49, "description": "Helike is a retrograde irregular moon of Jupiter.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Yanga R. Fernández, and Eugene A. Magnier in 2003."},
    {"name": "Orthosie", "extendsPlanet": "Jupiter", "size": 2.6, "position": 96, "rotationSpeed": 0.372, "orbitSpeed": 0.50, "id_planet": 6, "sizeOriginal": 30, "positionOriginal": 20680580, "rotationSpeedOriginal": 0.372, "orbitSpeedOriginal": 0.50, "description": "Orthosie is a retrograde irregular moon of Jupiter.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Yanga R. Fernández, and Eugene A. Magnier in 2003."},
    {"name": "Isonoe", "extendsPlanet": "Jupiter", "size": 2.4, "position": 97, "rotationSpeed": 0.410, "orbitSpeed": 0.51, "id_planet": 6, "sizeOriginal": 24, "positionOriginal": 18224140, "rotationSpeedOriginal": 0.410, "orbitSpeedOriginal": 0.51, "description": "Isonoe is a retrograde irregular moon of Jupiter.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Yanga R. Fernández, and Eugene A. Magnier in 2003."},
    {"name": "Thyone", "extendsPlanet": "Jupiter", "size": 2.2, "position": 98, "rotationSpeed": 0.450, "orbitSpeed": 0.52, "id_planet": 6, "sizeOriginal": 22, "positionOriginal": 15825690, "rotationSpeedOriginal": 0.450, "orbitSpeedOriginal": 0.52, "description": "Thyone is a retrograde irregular moon of Jupiter.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Yanga R. Fernández, and Eugene A. Magnier in 2003."},
    {"name": "Hermippe", "extendsPlanet": "Jupiter", "size": 2.0, "position": 99, "rotationSpeed": 0.490, "orbitSpeed": 0.53, "id_planet": 6, "sizeOriginal": 20, "positionOriginal": 13435370, "rotationSpeedOriginal": 0.490, "orbitSpeedOriginal": 0.53, "description": "Hermippe is a retrograde irregular moon of Jupiter.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Yanga R. Fernández, and Eugene A. Magnier in 2003."},
    {"name": "Aitne", "extendsPlanet": "Jupiter", "size": 2.3, "position": 103, "rotationSpeed": 0.421, "orbitSpeed": 0.54, "id_planet": 6, "sizeOriginal": 26, "positionOriginal": 14953140, "rotationSpeedOriginal": 0.421, "orbitSpeedOriginal": 0.54, "description": "Aitne is a retrograde irregular moon of Jupiter.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Yanga R. Fernández, and Eugene A. Magnier in 2003."},
    {"name": "Eurydome", "extendsPlanet": "Jupiter", "size": 2.1, "position": 104, "rotationSpeed": 0.462, "orbitSpeed": 0.55, "id_planet": 6, "sizeOriginal": 24, "positionOriginal": 12552500, "rotationSpeedOriginal": 0.462, "orbitSpeedOriginal": 0.55, "description": "Eurydome is a retrograde irregular moon of Jupiter.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Yanga R. Fernández, and Eugene A. Magnier in 2003."},
    {"name": "Euanthe", "extendsPlanet": "Jupiter", "size": 1.9, "position": 105, "rotationSpeed": 0.503, "orbitSpeed": 0.56, "id_planet": 6, "sizeOriginal": 20, "positionOriginal": 10752400, "rotationSpeedOriginal": 0.503, "orbitSpeedOriginal": 0.56, "description": "Euanthe is a retrograde irregular moon of Jupiter.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Yanga R. Fernández, and Eugene A. Magnier in 2003."},
    {"name": "Euporie", "extendsPlanet": "Jupiter", "size": 1.7, "position": 106, "rotationSpeed": 0.544, "orbitSpeed": 0.57, "id_planet": 6, "sizeOriginal": 18, "positionOriginal": 8926940, "rotationSpeedOriginal": 0.544, "orbitSpeedOriginal": 0.57, "description": "Euporie is a retrograde irregular moon of Jupiter.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Yanga R. Fernández, and Eugene A. Magnier in 2003."},
    {"name": "Sponde", "extendsPlanet": "Jupiter", "size": 1.5, "position": 110, "rotationSpeed": 0.585, "orbitSpeed": 0.59, "id_planet": 6, "sizeOriginal": 14, "positionOriginal": 6297110, "rotationSpeedOriginal": 0.585, "orbitSpeedOriginal": 0.59, "description": "Sponde is a retrograde irregular moon of Jupiter.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Yanga R. Fernández, and Eugene A. Magnier in 2001."},
    {"name": "Kale", "extendsPlanet": "Jupiter", "size": 1.3, "position": 111, "rotationSpeed": 0.626, "orbitSpeed": 0.60, "id_planet": 6, "sizeOriginal": 12, "positionOriginal": 5663510, "rotationSpeedOriginal": 0.626, "orbitSpeedOriginal": 0.60, "description": "Kale is a retrograde irregular moon of Jupiter.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Yanga R. Fernández, and Eugene A. Magnier in 2001."},
    {"name": "Pasithee", "extendsPlanet": "Jupiter", "size": 1.1, "position": 112, "rotationSpeed": 0.667, "orbitSpeed": 0.61, "id_planet": 6, "sizeOriginal": 10, "positionOriginal": 5040230, "rotationSpeedOriginal": 0.667, "orbitSpeedOriginal": 0.61, "description": "Pasithee is a retrograde irregular moon of Jupiter.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Yanga R. Fernández, and Eugene A. Magnier in 2001."},
    {"name": "Hegemone", "extendsPlanet": "Jupiter", "size": 1.0, "position": 113, "rotationSpeed": 0.708, "orbitSpeed": 0.62, "id_planet": 6, "sizeOriginal": 8, "positionOriginal": 4499300, "rotationSpeedOriginal": 0.708, "orbitSpeedOriginal": 0.62, "description": "Hegemone is a retrograde irregular moon of Jupiter.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Yanga R. Fernández, and Eugene A. Magnier in 2003."},
    {"name": "Megaclite", "extendsPlanet": "Jupiter", "size": 0.8, "position": 114, "rotationSpeed": 0.749, "orbitSpeed": 0.63, "id_planet": 6, "sizeOriginal": 6, "positionOriginal": 3986700, "rotationSpeedOriginal": 0.749, "orbitSpeedOriginal": 0.63, "description": "Megaclite is a retrograde irregular moon of Jupiter.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Yanga R. Fernández, and Eugene A. Magnier in 2001."},
    {"name": "Taygete", "extendsPlanet": "Jupiter", "size": 2.9, "position": 118, "rotationSpeed": 0.790, "orbitSpeed": 0.64, "id_planet": 6, "sizeOriginal": 30, "positionOriginal": 3012330, "rotationSpeedOriginal": 0.790, "orbitSpeedOriginal": 0.64, "description": "Taygete is a retrograde irregular moon of Jupiter.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, and Jan T. Kleyna in 2001."},
    {"name": "Chaldene", "extendsPlanet": "Jupiter", "size": 2.7, "position": 119, "rotationSpeed": 0.831, "orbitSpeed": 0.65, "id_planet": 6, "sizeOriginal": 30, "positionOriginal": 2807060, "rotationSpeedOriginal": 0.831, "orbitSpeedOriginal": 0.65, "description": "Chaldene is a retrograde irregular moon of Jupiter.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, and Jan T. Kleyna in 2001."},
    {"name": "Erinome", "extendsPlanet": "Jupiter", "size": 2.5, "position": 120, "rotationSpeed": 0.872, "orbitSpeed": 0.66, "id_planet": 6, "sizeOriginal": 30, "positionOriginal": 2605920, "rotationSpeedOriginal": 0.872, "orbitSpeedOriginal": 0.66, "description": "Erinome is a retrograde irregular moon of Jupiter.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, and Jan T. Kleyna in 2001."},
    {"name": "S/2017 J 4", "extendsPlanet": "Jupiter", "size": 2.3, "position": 121, "rotationSpeed": 0.913, "orbitSpeed": 0.67, "id_planet": 6, "sizeOriginal": 30, "positionOriginal": 2409010, "rotationSpeedOriginal": 0.913, "orbitSpeedOriginal": 0.67, "description": "S/2017 J 4 is a retrograde irregular moon of Jupiter.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, and Jan T. Kleyna in 2017."},
    {"name": "S/2011 J 2", "extendsPlanet": "Jupiter", "size": 2.1, "position": 122, "rotationSpeed": 0.954, "orbitSpeed": 0.68, "id_planet": 6, "sizeOriginal": 30, "positionOriginal": 2207430, "rotationSpeedOriginal": 0.954, "orbitSpeedOriginal": 0.68, "description": "S/2011 J 2 is a retrograde irregular moon of Jupiter.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, and Jan T. Kleyna in 2011."},
    {"name": "Eukelade", "extendsPlanet": "Jupiter", "size": 1.9, "position": 126, "rotationSpeed": 1.035, "orbitSpeed": 0.70, "id_planet": 6, "sizeOriginal": 20, "positionOriginal": 1840590, "rotationSpeedOriginal": 1.035, "orbitSpeedOriginal": 0.70, "description": "Eukelade is a retrograde irregular moon of Jupiter.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Jan T. Kleyna, and Gareth V. Williams in 2003."},
    {"name": "S/2017 J 7", "extendsPlanet": "Jupiter", "size": 1.7, "position": 127, "rotationSpeed": 1.076, "orbitSpeed": 0.71, "id_planet": 6, "sizeOriginal": 20, "positionOriginal": 1656970, "rotationSpeedOriginal": 1.076, "orbitSpeedOriginal": 0.71, "description": "S/2017 J 7 is a retrograde irregular moon of Jupiter.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Jan T. Kleyna, and Gareth V. Williams in 2017."},
    {"name": "Philophrosyne", "extendsPlanet": "Jupiter", "size": 1.5, "position": 128, "rotationSpeed": 1.117, "orbitSpeed": 0.72, "id_planet": 6, "sizeOriginal": 20, "positionOriginal": 1472200, "rotationSpeedOriginal": 1.117, "orbitSpeedOriginal": 0.72, "description": "Philophrosyne is a retrograde irregular moon of Jupiter.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Jan T. Kleyna, and Gareth V. Williams in 2017."},
    {"name": "S/2017 J 3", "extendsPlanet": "Jupiter", "size": 1.3, "position": 129, "rotationSpeed": 1.158, "orbitSpeed": 0.73, "id_planet": 6, "sizeOriginal": 20, "positionOriginal": 1304870, "rotationSpeedOriginal": 1.158, "orbitSpeedOriginal": 0.73, "description": "S/2017 J 3 is a retrograde irregular moon of Jupiter.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Jan T. Kleyna, and Gareth V. Williams in 2017."},
    {"name": "Cyllene", "extendsPlanet": "Jupiter", "size": 1.1, "position": 135, "rotationSpeed": 1.322, "orbitSpeed": 0.77, "id_planet": 6, "sizeOriginal": 20, "positionOriginal": 987200, "rotationSpeedOriginal": 1.322, "orbitSpeedOriginal": 0.77, "description": "Cyllene is a retrograde irregular moon of Jupiter.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Jan T. Kleyna, and Gareth V. Williams in 2003."},
    {"name": "S/2011 J 1", "extendsPlanet": "Jupiter", "size": 0.9, "position": 136, "rotationSpeed": 1.363, "orbitSpeed": 0.78, "id_planet": 6, "sizeOriginal": 20, "positionOriginal": 819140, "rotationSpeedOriginal": 1.363, "orbitSpeedOriginal": 0.78, "description": "S/2011 J 1 is a retrograde irregular moon of Jupiter.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Jan T. Kleyna, and Gareth V. Williams in 2011."},
    {"name": "S/2003 J 23", "extendsPlanet": "Jupiter", "size": 0.7, "position": 137, "rotationSpeed": 1.404, "orbitSpeed": 0.79, "id_planet": 6, "sizeOriginal": 20, "positionOriginal": 650750, "rotationSpeedOriginal": 1.404, "orbitSpeedOriginal": 0.79, "description": "S/2003 J 23 is a retrograde irregular moon of Jupiter.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Jan T. Kleyna, and Gareth V. Williams in 2003."},
    {"name": "S/2017 J 9", "extendsPlanet": "Jupiter", "size": 0.5, "position": 138, "rotationSpeed": 1.445, "orbitSpeed": 0.80, "id_planet": 6, "sizeOriginal": 20, "positionOriginal": 482700, "rotationSpeedOriginal": 1.445, "orbitSpeedOriginal": 0.80, "description": "S/2017 J 9 is a retrograde irregular moon of Jupiter.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Jan T. Kleyna, and Gareth V. Williams in 2017."},
    {"name": "S/2003 J 2", "extendsPlanet": "Jupiter", "size": 0.3, "position": 139, "rotationSpeed": 1.486, "orbitSpeed": 0.81, "id_planet": 6, "sizeOriginal": 20, "positionOriginal": 317370, "rotationSpeedOriginal": 1.486, "orbitSpeedOriginal": 0.81, "description": "S/2003 J 2 is a retrograde irregular moon of Jupiter.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Jan T. Kleyna, and Gareth V. Williams in 2003."},
    {"name": "S/2017 J 8", "extendsPlanet": "Jupiter", "size": 0.1, "position": 140, "rotationSpeed": 1.527, "orbitSpeed": 0.82, "id_planet": 6, "sizeOriginal": 20, "positionOriginal": 154040, "rotationSpeedOriginal": 1.527, "orbitSpeedOriginal": 0.82, "description": "S/2017 J 8 is a retrograde irregular moon of Jupiter.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Jan T. Kleyna, and Gareth V. Williams in 2017."},

    # Saturn's moons
    { "name": "Mimas", "extendsPlanet": "Saturn", "size": 0.8, "position": 17, "rotationSpeed": 0.029, "orbitSpeed": 0.005, "id_planet": 7, "sizeOriginal": 396.4, "positionOriginal": 185539, "rotationSpeedOriginal": 0.942, "orbitSpeedOriginal": 5.76,
      "description": "Mimas is known for its large impact crater called Herschel.", "history": "It was discovered by William Herschel in 1789." },
    { "name": "Rhea", "extendsPlanet": "Saturn", "size": 1.4, "position": 20, "rotationSpeed": 0.024, "orbitSpeed": 0.004, "id_planet": 7, "sizeOriginal": 1529.4, "positionOriginal": 527108, "rotationSpeedOriginal": 4.518, "orbitSpeedOriginal": 3.6,
      "description": "Rhea is Saturn's second-largest moon and has a heavily cratered surface.", "history": "It was discovered by Giovanni Cassini in 1672." },
    { "name": "Dione", "extendsPlanet": "Saturn", "size": 2.6, "position": 25, "rotationSpeed": 0.026, "orbitSpeed": 0.007, "id_planet": 7, "sizeOriginal": 1122.8, "positionOriginal": 377396, "rotationSpeedOriginal": 2.736, "orbitSpeedOriginal": 10.8,
      "description": "Dione is known for its heavily cratered surface and bright streaks.", "history": "It was discovered by Giovanni Cassini in 1684." },
    { "name": "Iapetus", "extendsPlanet": "Saturn", "size": 1.8, "position": 30, "rotationSpeed": 0.031, "orbitSpeed": 0.006, "id_planet": 7, "sizeOriginal": 1471.6, "positionOriginal": 3560820, "rotationSpeedOriginal": 79.321, "orbitSpeedOriginal": 108,
      "description": "Iapetus has a striking two-tone coloration and is known for its equatorial ridge.", "history": "It was discovered by Giovanni Cassini in 1671." },
    { "name": "Titan", "extendsPlanet": "Saturn", "size": 5.0, "position": 37, "rotationSpeed": 0.021, "orbitSpeed": 0.003, "id_planet": 7, "sizeOriginal": 5150, "positionOriginal": 1221870, "rotationSpeedOriginal": 15.945, "orbitSpeedOriginal": 21.24,
      "description": "Titan is the largest moon of Saturn and has a thick atmosphere.", "history": "It was discovered by Christiaan Huygens in 1655." },
    { "name": "Phoebe", "extendsPlanet": "Saturn", "size": 2.5, "position": 40, "rotationSpeed": 0.021, "orbitSpeed": 0.002, "id_planet": 7, "sizeOriginal": 213, "positionOriginal": 12952000, "rotationSpeedOriginal": 9.273, "orbitSpeedOriginal": 550.8, "description": "Phoebe is a irregular moon with a retrograde orbit.", "history": "It was discovered by William Henry Pickering in 1898." },
    { "name": "Hyperion", "extendsPlanet": "Saturn", "size": 2.3, "position": 45, "rotationSpeed": 0.13, "orbitSpeed": 0.005, "id_planet": 7, "sizeOriginal": 266, "positionOriginal": 1481010, "rotationSpeedOriginal": 13.39, "orbitSpeedOriginal": 21.28, "description": "Hyperion is known for its irregular shape and chaotic rotation.", "history": "It was discovered by William Cranch Bond in 1848." },
    {"name": "Enceladus", "extendsPlanet": "Saturn", "size": 1.4, "position": 55, "rotationSpeed": 0.000784, "orbitSpeed": 0.0013, "id_planet": 7, "sizeOriginal": 504.2, "positionOriginal": 237948, "rotationSpeedOriginal": 1.378, "orbitSpeedOriginal": 14.32, "description": "Enceladus is known for its active geysers and icy surface.", "history": "It was discovered by William Herschel in 1789."},
    {"name": "Tethys", "extendsPlanet": "Saturn", "size": 1.1, "position": 65, "rotationSpeed": 0.000675, "orbitSpeed": 0.0022, "id_planet": 7, "sizeOriginal": 1074.4, "positionOriginal": 294619, "rotationSpeedOriginal": 1.888, "orbitSpeedOriginal": 16.56, "description": "Tethys has a heavily cratered surface and a large impact crater called Odysseus.", "history": "It was discovered by Giovanni Cassini in 1684."},
    {"name": "Methone", "extendsPlanet": "Saturn", "size": 0.008, "position": 9.5, "rotationSpeed": 0.016, "orbitSpeed": 0.0011, "id_planet": 7, "sizeOriginal": 3.2, "positionOriginal": 194440, "rotationSpeedOriginal": 0.672, "orbitSpeedOriginal": 12.32, "description": "Methone is a small moon with a smooth surface and an elongated shape.", "history": "It was discovered by the Cassini Imaging Team in 2004."},
    {"name": "Helene", "extendsPlanet": "Saturn", "size": 0.2, "position": 23, "rotationSpeed": 0.0015, "orbitSpeed": 0.0038, "id_planet": 7, "sizeOriginal": 35.2, "positionOriginal": 377396, "rotationSpeedOriginal": 2.136, "orbitSpeedOriginal": 33.84, "description": "Helene shares its orbit with the larger moon Dione and is considered a Trojan moon. It has a relatively smooth surface and is believed to be a captured asteroid or a fragment from a collision.", "history": "It was discovered by Pierre Laques and Jean Lecacheux in 1980."},
    {"name": "Atlas", "extendsPlanet": "Saturn", "size": 0.3, "position": 28, "rotationSpeed": 0.0032, "orbitSpeed": 0.0042, "id_planet": 7, "sizeOriginal": 49.6, "positionOriginal": 137670, "rotationSpeedOriginal": 2.304, "orbitSpeedOriginal": 45.36, "description": "Atlas is characterized by its unique equatorial ridge and prominent ring-formation role. It's one of the innermost moons of Saturn and helps shape the edges of the A ring through gravitational interactions.", "history": "It was discovered by Richard Terrile in 1980 during the Voyager 1 mission."},
    {"name": "Janus", "extendsPlanet": "Saturn", "size": 0.2, "position": 21, "rotationSpeed": 0.0017, "orbitSpeed": 0.0041, "id_planet": 7, "sizeOriginal": 179.8, "positionOriginal": 151450, "rotationSpeedOriginal": 2.448, "orbitSpeedOriginal": 38.88, "description": "Janus is a co-orbital moon with Epimetheus and has a slightly irregular shape. It shares an orbit with Epimetheus and their gravitational interaction leads to periodic 'gigantic' collisions.", "history": "It was discovered by Audouin Dollfus in 1966."},
    {"name": "Epimetheus", "extendsPlanet": "Saturn", "size": 0.6, "position": 22, "rotationSpeed": 0.0016, "orbitSpeed": 0.0040, "id_planet": 7, "sizeOriginal": 144.2, "positionOriginal": 151422, "rotationSpeedOriginal": 2.304, "orbitSpeedOriginal": 37.44, "description": "Epimetheus shares its orbit with Janus and is known for its close relationship with that moon. They engage in a dance of orbital exchange.", "history": "It was discovered by Richard L. Walker in 1966."},
    {"name": "Telesto", "extendsPlanet": "Saturn", "size": 0.2, "position": 24, "rotationSpeed": 0.0020, "orbitSpeed": 0.0042, "id_planet": 7, "sizeOriginal": 24.8, "positionOriginal": 294619, "rotationSpeedOriginal": 2.88, "orbitSpeedOriginal": 43.68, "description": "Telesto is a co-orbital moon of Tethys and shares its orbit with Calypso. It's irregularly shaped and orbits in the Lagrange point of Tethys's leading L4.", "history": "It was discovered by Bradford A. Smith, Harold Reitsema, and Stephen M. Larson in 1980."},
    {"name": "Calypso", "extendsPlanet": "Saturn", "size": 0.2, "position": 25, "rotationSpeed": 0.0019, "orbitSpeed": 0.0044, "id_planet": 7, "sizeOriginal": 30.2, "positionOriginal": 294619, "rotationSpeedOriginal": 2.736, "orbitSpeedOriginal": 50.4, "description": "Calypso is a co-orbital moon of Tethys and shares its orbit with Telesto. Its irregular shape and unique orbit make it an intriguing moon to study.", "history": "It was discovered by Dan Pascu, P. Kenneth Seidelmann, William A. Baum, and Douglas G. Currie in 1980."},
    {"name": "Prometheus", "extendsPlanet": "Saturn", "size": 0.5, "position": 29, "rotationSpeed": 0.004, "orbitSpeed": 0.0048, "id_planet": 7, "sizeOriginal": 86.2, "positionOriginal": 139353.5, "rotationSpeedOriginal": 2.832, "orbitSpeedOriginal": 44.16, "description": "Prometheus is a shepherd moon for Saturn's F ring, sculpting the ring's shape through gravitational interactions. It has a potato-like shape due to its proximity to the planet.", "history": "It was discovered by Stewart A. Collins and Richard J. Terrile in 1980."},
    {"name": "Pandora", "extendsPlanet": "Saturn", "size": 0.5, "position": 30, "rotationSpeed": 0.005, "orbitSpeed": 0.0046, "id_planet": 7, "sizeOriginal": 81.4, "positionOriginal": 141700, "rotationSpeedOriginal": 3.6, "orbitSpeedOriginal": 45.36, "description": "Pandora is another shepherd moon of the F ring, located just outside it. Its irregular shape and close relationship with Prometheus contribute to the ring's features.", "history": "It was discovered by Stewart A. Collins and Richard J. Terrile in 1980."},
    {"name": "Pan", "extendsPlanet": "Saturn", "size": 0.3, "position": 31, "rotationSpeed": 0.0035, "orbitSpeed": 0.0047, "id_planet": 7, "sizeOriginal": 35.2, "positionOriginal": 133583.5, "rotationSpeedOriginal": 2.52, "orbitSpeedOriginal": 44.64, "description": "Pan is a moon within the Encke Gap of Saturn's A ring. Its distinctive equatorial ridge and shaping of the gap make it a remarkable moon.", "history": "It was discovered by Mark R. Showalter in 1990."},
    {"name": "Ymir", "extendsPlanet": "Saturn", "size": 2.3, "position": 32, "rotationSpeed": 0.009, "orbitSpeed": 0.0045, "id_planet": 7, "sizeOriginal": 18.2, "positionOriginal": 231154, "rotationSpeedOriginal": 1.944, "orbitSpeedOriginal": 44.1, "description": "Ymir is a retrograde irregular moon with a very distant and inclined orbit. Its name comes from Norse mythology.", "history": "It was discovered by Brett J. Gladman, John J. Kavelaars, Jean-Marc Petit, Hans Scholl, Matthew J. Holman, Brian G. Marsden, Phillip D. Nicholson, and Joseph A. Burns in 2000."},
    {"name": "Paaliaq", "extendsPlanet": "Saturn", "size": 1.0, "position": 33, "rotationSpeed": 0.0028, "orbitSpeed": 0.0049, "id_planet": 7, "sizeOriginal": 22.6, "positionOriginal": 152759, "rotationSpeedOriginal": 2.016, "orbitSpeedOriginal": 45.72, "description": "Paaliaq is a prograde irregular moon with a distant orbit. Its name comes from Inuit mythology.", "history": "It was discovered by Brett J. Gladman, John J. Kavelaars, Matthew J. Holman, Jean-Marc Petit, Hans Scholl, and Brian G. Marsden in 2000."},
    {"name": "Tarvos", "extendsPlanet": "Saturn", "size": 0.9, "position": 34, "rotationSpeed": 0.0026, "orbitSpeed": 0.0051, "id_planet": 7, "sizeOriginal": 15.2, "positionOriginal": 185279, "rotationSpeedOriginal": 1.872, "orbitSpeedOriginal": 46.44, "description": "Tarvos is a retrograde irregular moon with a distant and inclined orbit. It is one of the outermost known moons of Saturn.", "history": "It was discovered by Brett J. Gladman, John J. Kavelaars, Matthew J. Holman, Jean-Marc Petit, Hans Scholl, and Brian G. Marsden in 2000."},
    {"name": "Ijiraq", "extendsPlanet": "Saturn", "size": 0.8, "position": 35, "rotationSpeed": 0.0024, "orbitSpeed": 0.0052, "id_planet": 7, "sizeOriginal": 12.6, "positionOriginal": 110944, "rotationSpeedOriginal": 1.728, "orbitSpeedOriginal": 47.04, "description": "Ijiraq is a prograde irregular moon with a distant orbit. Its name comes from Inuit mythology.", "history": "It was discovered by Brett J. Gladman, John J. Kavelaars, Matthew J. Holman, Jean-Marc Petit, Hans Scholl, and Brian G. Marsden in 2000."},
    {"name": "Suttungr", "extendsPlanet": "Saturn", "size": 1.2, "position": 36, "rotationSpeed": 0.0023, "orbitSpeed": 0.0053, "id_planet": 7, "sizeOriginal": 7.6, "positionOriginal": 194715, "rotationSpeedOriginal": 1.656, "orbitSpeedOriginal": 47.52, "description": "Suttungr is a retrograde irregular moon with a very distant and inclined orbit. Its name comes from Norse mythology.", "history": "It was discovered by Brett J. Gladman, John J. Kavelaars, Matthew J. Holman, Jean-Marc Petit, Hans Scholl, and Brian G. Marsden in 2000."},
    {"name": "Kiviuq", "extendsPlanet": "Saturn", "size": 0.9, "position": 37, "rotationSpeed": 0.0021, "orbitSpeed": 0.0054, "id_planet": 7, "sizeOriginal": 16.2, "positionOriginal": 144497, "rotationSpeedOriginal": 1.512, "orbitSpeedOriginal": 48.24, "description": "Kiviuq is a prograde irregular moon with a distant and inclined orbit. Its name comes from Inuit mythology.", "history": "It was discovered by Brett J. Gladman, John J. Kavelaars, Matthew J. Holman, Jean-Marc Petit, Hans Scholl, and Brian G. Marsden in 2000."},
    {"name": "Mundilfari", "extendsPlanet": "Saturn", "size": 0.5, "position": 38, "rotationSpeed": 0.0020, "orbitSpeed": 0.0055, "id_planet": 7, "sizeOriginal": 27.4, "positionOriginal": 186207, "rotationSpeedOriginal": 1.44, "orbitSpeedOriginal": 48.96, "description": "Mundilfari is a retrograde irregular moon with a distant and inclined orbit. Its name comes from Norse mythology.", "history": "It was discovered by Brett J. Gladman, John J. Kavelaars, Matthew J. Holman, Jean-Marc Petit, Hans Scholl, and Brian G. Marsden in 2000."},
    {"name": "Albiorix", "extendsPlanet": "Saturn", "size": 1.1, "position": 39, "rotationSpeed": 0.0024, "orbitSpeed": 0.0056, "id_planet": 7, "sizeOriginal": 32.4, "positionOriginal": 165588, "rotationSpeedOriginal": 1.728, "orbitSpeedOriginal": 49.68, "description": "Albiorix is a retrograde irregular moon with a distant and inclined orbit. Its name comes from the Gallic god Albiorix.", "history": "It was discovered by Matthew J. Holman, Brett J. Gladman, John J. Kavelaars, Jean-Marc Petit, Hans Scholl, and Brian G. Marsden in 2000."},
    {"name": "Skathi", "extendsPlanet": "Saturn", "size": 1.0, "position": 40, "rotationSpeed": 0.0022, "orbitSpeed": 0.0057, "id_planet": 7, "sizeOriginal": 35.0, "positionOriginal": 155404, "rotationSpeedOriginal": 1.584, "orbitSpeedOriginal": 50.4, "description": "Skathi is a prograde irregular moon with a distant and inclined orbit. Its name comes from Norse mythology.", "history": "It was discovered by Brett J. Gladman, John J. Kavelaars, Matthew J. Holman, Jean-Marc Petit, Hans Scholl, and Brian G. Marsden in 2000."},
    {"name": "Erriapus", "extendsPlanet": "Saturn", "size": 0.6, "position": 41, "rotationSpeed": 0.0021, "orbitSpeed": 0.0058, "id_planet": 7, "sizeOriginal": 14.0, "positionOriginal": 175950, "rotationSpeedOriginal": 1.512, "orbitSpeedOriginal": 51.12, "description": "Erriapus is a prograde irregular moon with a distant and inclined orbit. Its name comes from the Gallic god Erriapus.", "history": "It was discovered by Matthew J. Holman, Brett J. Gladman, John J. Kavelaars, Jean-Marc Petit, Hans Scholl, and Brian G. Marsden in 2000."},
    {"name": "Siarnaq", "extendsPlanet": "Saturn", "size": 0.8, "position": 42, "rotationSpeed": 0.0025, "orbitSpeed": 0.0059, "id_planet": 7, "sizeOriginal": 22.0, "positionOriginal": 181500, "rotationSpeedOriginal": 1.8, "orbitSpeedOriginal": 52.56, "description": "Siarnaq is a prograde irregular moon with a distant and inclined orbit. Its name comes from Inuit mythology.", "history": "It was discovered by Brett J. Gladman, John J. Kavelaars, Matthew J. Holman, Jean-Marc Petit, Hans Scholl, and Brian G. Marsden in 2000."},
    {"name": "Thrymr", "extendsPlanet": "Saturn", "size": 0.5, "position": 43, "rotationSpeed": 0.0023, "orbitSpeed": 0.0060, "id_planet": 7, "sizeOriginal": 7.6, "positionOriginal": 204264, "rotationSpeedOriginal": 1.656, "orbitSpeedOriginal": 54.0, "description": "Thrymr is a retrograde irregular moon with a distant and inclined orbit. Its name comes from Norse mythology.", "history": "It was discovered by Brett J. Gladman, John J. Kavelaars, Matthew J. Holman, Jean-Marc Petit, Hans Scholl, and Brian G. Marsden in 2000."},
    {"name": "Narvi", "extendsPlanet": "Saturn", "size": 0.4, "position": 44, "rotationSpeed": 0.0021, "orbitSpeed": 0.0061, "id_planet": 7, "sizeOriginal": 6.4, "positionOriginal": 192556, "rotationSpeedOriginal": 1.512, "orbitSpeedOriginal": 55.44, "description": "Narvi is a retrograde irregular moon with a distant and inclined orbit. Its name comes from Norse mythology.", "history": "It was discovered by Brett J. Gladman, John J. Kavelaars, Matthew J. Holman, Jean-Marc Petit, Hans Scholl, and Brian G. Marsden in 2003."},
    {"name": "Methone", "extendsPlanet": "Saturn", "size": 0.2, "position": 45, "rotationSpeed": 0.0020, "orbitSpeed": 0.0062, "id_planet": 7, "sizeOriginal": 2.6, "positionOriginal": 194440, "rotationSpeedOriginal": 1.44, "orbitSpeedOriginal": 56.16, "description": "Methone is a prograde irregular moon with a distant orbit. It was discovered during the Cassini spacecraft's mission to Saturn.", "history": "It was discovered by the Cassini Imaging Science Team in 2004."},
    {"name": "Pallene", "extendsPlanet": "Saturn", "size": 0.4, "position": 46, "rotationSpeed": 0.0023, "orbitSpeed": 0.0063, "id_planet": 7, "sizeOriginal": 4.4, "positionOriginal": 212280, "rotationSpeedOriginal": 1.656, "orbitSpeedOriginal": 57.24, "description": "Pallene is a prograde irregular moon with a distant orbit. It was discovered during the Cassini spacecraft's mission to Saturn.", "history": "It was discovered by the Cassini Imaging Science Team in 2004."},
    {"name": "Polydeuces", "extendsPlanet": "Saturn", "size": 0.3, "position": 47, "rotationSpeed": 0.0021, "orbitSpeed": 0.0064, "id_planet": 7, "sizeOriginal": 3.2, "positionOriginal": 377396, "rotationSpeedOriginal": 1.512, "orbitSpeedOriginal": 58.32, "description": "Polydeuces is a prograde irregular moon with a distant orbit. It was discovered during the Cassini spacecraft's mission to Saturn.", "history": "It was discovered by the Cassini Imaging Science Team in 2004."},
    {"name": "Daphnis", "extendsPlanet": "Saturn", "size": 0.1, "position": 48, "rotationSpeed": 0.0018, "orbitSpeed": 0.0065, "id_planet": 7, "sizeOriginal": 8.0, "positionOriginal": 136505, "rotationSpeedOriginal": 1.296, "orbitSpeedOriginal": 59.4, "description": "Daphnis is a prograde moon that orbits within the Keeler Gap of Saturn's A ring. It creates a wavy pattern within the ring due to gravitational interactions.", "history": "It was discovered by the Cassini Imaging Science Team in 2005."},
    {"name": "Aegir", "extendsPlanet": "Saturn", "size": 0.3, "position": 49, "rotationSpeed": 0.0022, "orbitSpeed": 0.0066, "id_planet": 7, "sizeOriginal": 7.0, "positionOriginal": 207967, "rotationSpeedOriginal": 1.584, "orbitSpeedOriginal": 60.48, "description": "Aegir is a retrograde irregular moon with a distant and inclined orbit. Its name comes from Norse mythology.", "history": "It was discovered by Brett J. Gladman, John J. Kavelaars, Jean-Marc Petit, Hans Scholl, Matthew J. Holman, Brian G. Marsden, and Phillip D. Nicholson in 2004."},
    {"name": "Bebhionn", "extendsPlanet": "Saturn", "size": 0.3, "position": 50, "rotationSpeed": 0.0021, "orbitSpeed": 0.0067, "id_planet": 7, "sizeOriginal": 6.4, "positionOriginal": 171142, "rotationSpeedOriginal": 1.512, "orbitSpeedOriginal": 61.56, "description": "Bebhionn is a prograde irregular moon with a distant orbit. Its name comes from Celtic mythology.", "history": "It was discovered by Brett J. Gladman, John J. Kavelaars, Jean-Marc Petit, Hans Scholl, Matthew J. Holman, Brian G. Marsden, and Phillip D. Nicholson in 2004."},
    {"name": "Bergelmir", "extendsPlanet": "Saturn", "size": 0.3, "position": 51, "rotationSpeed": 0.0023, "orbitSpeed": 0.0068, "id_planet": 7, "sizeOriginal": 7.6, "positionOriginal": 196200, "rotationSpeedOriginal": 1.656, "orbitSpeedOriginal": 62.64, "description": "Bergelmir is a retrograde irregular moon with a distant and inclined orbit. Its name comes from Norse mythology.", "history": "It was discovered by Brett J. Gladman, John J. Kavelaars, Jean-Marc Petit, Hans Scholl, Matthew J. Holman, Brian G. Marsden, and Phillip D. Nicholson in 2004."},
    {"name": "Bestla", "extendsPlanet": "Saturn", "size": 0.3, "position": 52, "rotationSpeed": 0.0021, "orbitSpeed": 0.0069, "id_planet": 7, "sizeOriginal": 6.4, "positionOriginal": 220000, "rotationSpeedOriginal": 1.512, "orbitSpeedOriginal": 63.72, "description": "Bestla is a retrograde irregular moon with a distant and inclined orbit. Its name comes from Norse mythology.", "history": "It was discovered by Brett J. Gladman, John J. Kavelaars, Jean-Marc Petit, Hans Scholl, Matthew J. Holman, Brian G. Marsden, and Phillip D. Nicholson in 2004."},
    {"name": "Farbauti", "extendsPlanet": "Saturn", "size": 0.4, "position": 53, "rotationSpeed": 0.0024, "orbitSpeed": 0.0070, "id_planet": 7, "sizeOriginal": 5.4, "positionOriginal": 222500, "rotationSpeedOriginal": 1.728, "orbitSpeedOriginal": 64.8, "description": "Farbauti is a retrograde irregular moon with a distant and inclined orbit. Its name comes from Norse mythology.", "history": "It was discovered by Brett J. Gladman, John J. Kavelaars, Jean-Marc Petit, Hans Scholl, Matthew J. Holman, Brian G. Marsden, and Phillip D. Nicholson in 2004."},
    {"name": "Fenrir", "extendsPlanet": "Saturn", "size": 0.5, "position": 54, "rotationSpeed": 0.0025, "orbitSpeed": 0.0071, "id_planet": 7, "sizeOriginal": 8.6, "positionOriginal": 250086, "rotationSpeedOriginal": 1.8, "orbitSpeedOriginal": 65.88, "description": "Fenrir is a retrograde irregular moon with a distant and inclined orbit. Its name comes from Norse mythology.", "history": "It was discovered by Brett J. Gladman, John J. Kavelaars, Jean-Marc Petit, Hans Scholl, Matthew J. Holman, Brian G. Marsden, and Phillip D. Nicholson in 2004."},
    {"name": "Fornjot", "extendsPlanet": "Saturn", "size": 0.4, "position": 55, "rotationSpeed": 0.0024, "orbitSpeed": 0.0072, "id_planet": 7, "sizeOriginal": 7.4, "positionOriginal": 211400, "rotationSpeedOriginal": 1.728, "orbitSpeedOriginal": 67.08, "description": "Fornjot is a retrograde irregular moon with a distant and inclined orbit. Its name comes from Norse mythology.", "history": "It was discovered by Brett J. Gladman, John J. Kavelaars, Jean-Marc Petit, Hans Scholl, Matthew J. Holman, Brian G. Marsden, and Phillip D. Nicholson in 2004."},
    {"name": "Hati", "extendsPlanet": "Saturn", "size": 0.4, "position": 56, "rotationSpeed": 0.0023, "orbitSpeed": 0.0073, "id_planet": 7, "sizeOriginal": 7.0, "positionOriginal": 211401, "rotationSpeedOriginal": 1.656, "orbitSpeedOriginal": 68.28, "description": "Hati is a retrograde irregular moon with a distant and inclined orbit. Its name comes from Norse mythology.", "history": "It was discovered by Brett J. Gladman, John J. Kavelaars, Jean-Marc Petit, Hans Scholl, Matthew J. Holman, Brian G. Marsden, and Phillip D. Nicholson in 2004."},
    {"name": "Hyrrokkin", "extendsPlanet": "Saturn", "size": 0.6, "position": 57, "rotationSpeed": 0.0027, "orbitSpeed": 0.0074, "id_planet": 7, "sizeOriginal": 11.4, "positionOriginal": 213850, "rotationSpeedOriginal": 1.944, "orbitSpeedOriginal": 69.48, "description": "Hyrrokkin is a retrograde irregular moon with a distant and inclined orbit. Its name comes from Norse mythology.", "history": "It was discovered by Brett J. Gladman, John J. Kavelaars, Jean-Marc Petit, Hans Scholl, Matthew J. Holman, Brian G. Marsden, and Phillip D. Nicholson in 2006."},
    {"name": "Kari", "extendsPlanet": "Saturn", "size": 0.5, "position": 58, "rotationSpeed": 0.0026, "orbitSpeed": 0.0075, "id_planet": 7, "sizeOriginal": 8.8, "positionOriginal": 210563, "rotationSpeedOriginal": 1.872, "orbitSpeedOriginal": 70.68, "description": "Kari is a retrograde irregular moon with a distant and inclined orbit. Its name comes from Norse mythology.", "history": "It was discovered by Brett J. Gladman, John J. Kavelaars, Jean-Marc Petit, Hans Scholl, Matthew J. Holman, Brian G. Marsden, and Phillip D. Nicholson in 2006."},
    {"name": "Loge", "extendsPlanet": "Saturn", "size": 0.3, "position": 59, "rotationSpeed": 0.0024, "orbitSpeed": 0.0076, "id_planet": 7, "sizeOriginal": 5.2, "positionOriginal": 193087, "rotationSpeedOriginal": 1.728, "orbitSpeedOriginal": 71.88, "description": "Loge is a retrograde irregular moon with a distant and inclined orbit. Its name comes from Norse mythology.", "history": "It was discovered by Brett J. Gladman, John J. Kavelaars, Jean-Marc Petit, Hans Scholl, Matthew J. Holman, Brian G. Marsden, and Phillip D. Nicholson in 2006."},
    {"name": "Skoll", "extendsPlanet": "Saturn", "size": 0.3, "position": 60, "rotationSpeed": 0.0023, "orbitSpeed": 0.0077, "id_planet": 7, "sizeOriginal": 6.4, "positionOriginal": 180000, "rotationSpeedOriginal": 1.656, "orbitSpeedOriginal": 73.08, "description": "Skoll is a retrograde irregular moon with a distant and inclined orbit. Its name comes from Norse mythology.", "history": "It was discovered by Brett J. Gladman, John J. Kavelaars, Jean-Marc Petit, Hans Scholl, Matthew J. Holman, Brian G. Marsden, and Phillip D. Nicholson in 2006."},
    {"name": "Surtur", "extendsPlanet": "Saturn", "size": 0.6, "position": 61, "rotationSpeed": 0.0025, "orbitSpeed": 0.0078, "id_planet": 7, "sizeOriginal": 11.8, "positionOriginal": 180100, "rotationSpeedOriginal": 1.8, "orbitSpeedOriginal": 74.28, "description": "Surtur is a retrograde irregular moon with a distant and inclined orbit. Its name comes from Norse mythology.", "history": "It was discovered by Brett J. Gladman, John J. Kavelaars, Jean-Marc Petit, Hans Scholl, Matthew J. Holman, Brian G. Marsden, and Phillip D. Nicholson in 2006."},
    {"name": "Anthe", "extendsPlanet": "Saturn", "size": 0.2, "position": 62, "rotationSpeed": 0.0024, "orbitSpeed": 0.0079, "id_planet": 7, "sizeOriginal": 2.0, "positionOriginal": 197700, "rotationSpeedOriginal": 1.728, "orbitSpeedOriginal": 75.48, "description": "Anthe is a prograde moon that orbits within the Keeler Gap of Saturn's A ring. It creates a wavy pattern within the ring due to gravitational interactions.", "history": "It was discovered by the Cassini Imaging Science Team in 2007."},
    {"name": "Jarnsaxa", "extendsPlanet": "Saturn", "size": 0.3, "position": 63, "rotationSpeed": 0.0026, "orbitSpeed": 0.0080, "id_planet": 7, "sizeOriginal": 6.4, "positionOriginal": 189200, "rotationSpeedOriginal": 1.872, "orbitSpeedOriginal": 76.68, "description": "Jarnsaxa is a retrograde irregular moon with a distant and inclined orbit. Its name comes from Norse mythology.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Jan T. Kleyna, and Brian G. Marsden in 2006."},
    {"name": "Greip", "extendsPlanet": "Saturn", "size": 0.3, "position": 64, "rotationSpeed": 0.0025, "orbitSpeed": 0.0081, "id_planet": 7, "sizeOriginal": 6.8, "positionOriginal": 184600, "rotationSpeedOriginal": 1.8, "orbitSpeedOriginal": 77.88, "description": "Greip is a retrograde irregular moon with a distant and inclined orbit. Its name comes from Norse mythology.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Jan T. Kleyna, and Brian G. Marsden in 2006."},
    {"name": "Tarqeq", "extendsPlanet": "Saturn", "size": 0.5, "position": 65, "rotationSpeed": 0.0024, "orbitSpeed": 0.0082, "id_planet": 7, "sizeOriginal": 8.0, "positionOriginal": 180000, "rotationSpeedOriginal": 1.728, "orbitSpeedOriginal": 79.08, "description": "Tarqeq is a prograde irregular moon with a distant and inclined orbit. Its name comes from Inuit mythology.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Jan T. Kleyna, and Brian G. Marsden in 2007."},
    {"name": "Aegaeon", "extendsPlanet": "Saturn", "size": 0.1, "position": 66, "rotationSpeed": 0.0023, "orbitSpeed": 0.0083, "id_planet": 7, "sizeOriginal": 1.7, "positionOriginal": 167500, "rotationSpeedOriginal": 1.656, "orbitSpeedOriginal": 80.28, "description": "Aegaeon is a prograde moon that orbits within the Encke Gap of Saturn's A ring. It creates a wavy pattern within the ring due to gravitational interactions.", "history": "It was discovered by the Cassini Imaging Science Team in 2008."},
    {"name": "Gridr", "extendsPlanet": "Saturn", "size": 0.3, "position": 67, "rotationSpeed": 0.0025, "orbitSpeed": 0.0084, "id_planet": 7, "sizeOriginal": 5.4, "positionOriginal": 177025, "rotationSpeedOriginal": 1.8, "orbitSpeedOriginal": 81.48, "description": "Gridr is a retrograde irregular moon with a distant and inclined orbit. Its name comes from Norse mythology.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Jan T. Kleyna, and Brian G. Marsden in 2006."},
    {"name": "Angrboda", "extendsPlanet": "Saturn", "size": 0.4, "position": 68, "rotationSpeed": 0.0026, "orbitSpeed": 0.0085, "id_planet": 7, "sizeOriginal": 6.6, "positionOriginal": 193050, "rotationSpeedOriginal": 1.872, "orbitSpeedOriginal": 82.68, "description": "Angrboda is a retrograde irregular moon with a distant and inclined orbit. Its name comes from Norse mythology.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Jan T. Kleyna, and Brian G. Marsden in 2004."},
    {"name": "Skrymir", "extendsPlanet": "Saturn", "size": 0.4, "position": 69, "rotationSpeed": 0.0027, "orbitSpeed": 0.0086, "id_planet": 7, "sizeOriginal": 6.0, "positionOriginal": 193000, "rotationSpeedOriginal": 1.944, "orbitSpeedOriginal": 83.88, "description": "Skrymir is a retrograde irregular moon with a distant and inclined orbit. Its name comes from Norse mythology.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Jan T. Kleyna, and Brian G. Marsden in 2006."},
    {"name": "Gerd", "extendsPlanet": "Saturn", "size": 0.3, "position": 70, "rotationSpeed": 0.0025, "orbitSpeed": 0.0087, "id_planet": 7, "sizeOriginal": 4.8, "positionOriginal": 180400, "rotationSpeedOriginal": 1.8, "orbitSpeedOriginal": 85.08, "description": "Gerd is a retrograde irregular moon with a distant and inclined orbit. Its name comes from Norse mythology.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Jan T. Kleyna, and Brian G. Marsden in 2006."},
    {"name": "S/2004 S 26", "extendsPlanet": "Saturn", "size": 0.2, "position": 71, "rotationSpeed": 0.0024, "orbitSpeed": 0.0088, "id_planet": 7, "sizeOriginal": 2.4, "positionOriginal": 186680, "rotationSpeedOriginal": 1.728, "orbitSpeedOriginal": 86.28, "description": "S/2004 S 26 is a prograde irregular moon with a distant and inclined orbit. It was discovered during the Cassini spacecraft's mission to Saturn.", "history": "It was discovered by the Cassini Imaging Science Team in 2004."},
    {"name": "Eggther", "extendsPlanet": "Saturn", "size": 0.3, "position": 72, "rotationSpeed": 0.0026, "orbitSpeed": 0.0089, "id_planet": 7, "sizeOriginal": 5.6, "positionOriginal": 186300, "rotationSpeedOriginal": 1.872, "orbitSpeedOriginal": 87.48, "description": "Eggther is a retrograde irregular moon with a distant and inclined orbit. Its name comes from Norse mythology.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Jan T. Kleyna, and Brian G. Marsden in 2006."},
    {"name": "S/2004 S 29", "extendsPlanet": "Saturn", "size": 0.2, "position": 73, "rotationSpeed": 0.0025, "orbitSpeed": 0.0090, "id_planet": 7, "sizeOriginal": 2.6, "positionOriginal": 185920, "rotationSpeedOriginal": 1.8, "orbitSpeedOriginal": 88.68, "description": "S/2004 S 29 is a prograde irregular moon with a distant and inclined orbit. It was discovered during the Cassini spacecraft's mission to Saturn.", "history": "It was discovered by the Cassini Imaging Science Team in 2004."},
    {"name": "Beli", "extendsPlanet": "Saturn", "size": 0.3, "position": 74, "rotationSpeed": 0.0024, "orbitSpeed": 0.0091, "id_planet": 7, "sizeOriginal": 4.8, "positionOriginal": 191200, "rotationSpeedOriginal": 1.728, "orbitSpeedOriginal": 89.88, "description": "Beli is a retrograde irregular moon with a distant and inclined orbit. Its name comes from Norse mythology.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Jan T. Kleyna, and Brian G. Marsden in 2004."},
    {"name": "Gunnlod", "extendsPlanet": "Saturn", "size": 0.4, "position": 75, "rotationSpeed": 0.0025, "orbitSpeed": 0.0092, "id_planet": 7, "sizeOriginal": 7.4, "positionOriginal": 202000, "rotationSpeedOriginal": 1.8, "orbitSpeedOriginal": 91.08, "description": "Gunnlod is a retrograde irregular moon with a distant and inclined orbit. Its name comes from Norse mythology.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Jan T. Kleyna, and Brian G. Marsden in 2006."},
    {"name": "Thiazzi", "extendsPlanet": "Saturn", "size": 0.3, "position": 76, "rotationSpeed": 0.0024, "orbitSpeed": 0.0093, "id_planet": 7, "sizeOriginal": 5.8, "positionOriginal": 196800, "rotationSpeedOriginal": 1.728, "orbitSpeedOriginal": 92.28, "description": "Thiazzi is a retrograde irregular moon with a distant and inclined orbit. Its name comes from Norse mythology.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Jan T. Kleyna, and Brian G. Marsden in 2006."},
    {"name": "S/2004 S 34", "extendsPlanet": "Saturn", "size": 0.2, "position": 77, "rotationSpeed": 0.0023, "orbitSpeed": 0.0094, "id_planet": 7, "sizeOriginal": 2.4, "positionOriginal": 198080, "rotationSpeedOriginal": 1.656, "orbitSpeedOriginal": 93.48, "description": "S/2004 S 34 is a prograde irregular moon with a distant and inclined orbit. It was discovered during the Cassini spacecraft's mission to Saturn.", "history": "It was discovered by the Cassini Imaging Science Team in 2004."},
    {"name": "Alvaldi", "extendsPlanet": "Saturn", "size": 0.3, "position": 78, "rotationSpeed": 0.0026, "orbitSpeed": 0.0095, "id_planet": 7, "sizeOriginal": 6.0, "positionOriginal": 200400, "rotationSpeedOriginal": 1.872, "orbitSpeedOriginal": 94.68, "description": "Alvaldi is a retrograde irregular moon with a distant and inclined orbit. Its name comes from Norse mythology.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Jan T. Kleyna, and Brian G. Marsden in 2007."},
    {"name": "Geirrod", "extendsPlanet": "Saturn", "size": 0.4, "position": 79, "rotationSpeed": 0.0025, "orbitSpeed": 0.0096, "id_planet": 7, "sizeOriginal": 6.6, "positionOriginal": 197800, "rotationSpeedOriginal": 1.8, "orbitSpeedOriginal": 95.88, "description": "Geirrod is a retrograde irregular moon with a distant and inclined orbit. Its name comes from Norse mythology.", "history": "It was discovered by Scott S. Sheppard, David C. Jewitt, Jan T. Kleyna, and Brian G. Marsden in 2006."},
    {"name": "S/2004 S 7", "extendsPlanet": "Saturn", "size": 0.2, "position": 80, "rotationSpeed": 0.0024, "orbitSpeed": 0.0097, "id_planet": 7, "sizeOriginal": 2.6, "positionOriginal": 197066, "rotationSpeedOriginal": 1.728, "orbitSpeedOriginal": 97.08, "description": "S/2004 S 7 is a prograde irregular moon with a distant and inclined orbit. It was discovered during the Cassini spacecraft's mission to Saturn.", "history": "It was discovered by the Cassini Imaging Science Team in 2004."},
    {"name": "S/2004 S 12", "extendsPlanet": "Saturn", "size": 0.2, "position": 81, "rotationSpeed": 0.0023, "orbitSpeed": 0.0098, "id_planet": 7, "sizeOriginal": 2.2, "positionOriginal": 209460, "rotationSpeedOriginal": 1.656, "orbitSpeedOriginal": 98.28, "description": "S/2004 S 12 is a prograde irregular moon with a distant and inclined orbit. It was discovered during the Cassini spacecraft's mission to Saturn.", "history": "It was discovered by the Cassini Imaging Science Team in 2004."},
    {"name": "S/2004 S 13", "extendsPlanet": "Saturn", "size": 0.2, "position": 82, "rotationSpeed": 0.0022, "orbitSpeed": 0.0099, "id_planet": 7, "sizeOriginal": 2.2, "positionOriginal": 210050, "rotationSpeedOriginal": 1.584, "orbitSpeedOriginal": 99.48, "description": "S/2004 S 13 is a prograde irregular moon with a distant and inclined orbit. It was discovered during the Cassini spacecraft's mission to Saturn.", "history": "It was discovered by the Cassini Imaging Science Team in 2004."},
    {"name": "S/2004 S 17", "extendsPlanet": "Saturn", "size": 0.2, "position": 83, "rotationSpeed": 0.0021, "orbitSpeed": 0.0100, "id_planet": 7, "sizeOriginal": 2.2, "positionOriginal": 208540, "rotationSpeedOriginal": 1.512, "orbitSpeedOriginal": 100.68, "description": "S/2004 S 17 is a prograde irregular moon with a distant and inclined orbit. It was discovered during the Cassini spacecraft's mission to Saturn.", "history": "It was discovered by the Cassini Imaging Science Team in 2004."},
    {"name": "S/2004 S 21", "extendsPlanet": "Saturn", "size": 0.2, "position": 84, "rotationSpeed": 0.0020, "orbitSpeed": 0.0101, "id_planet": 7, "sizeOriginal": 2.2, "positionOriginal": 204180, "rotationSpeedOriginal": 1.44, "orbitSpeedOriginal": 101.88, "description": "S/2004 S 21 is a prograde irregular moon with a distant and inclined orbit. It was discovered during the Cassini spacecraft's mission to Saturn.", "history": "It was discovered by the Cassini Imaging Science Team in 2004."},
    {"name": "S/2004 S 24", "extendsPlanet": "Saturn", "size": 0.2, "position": 85, "rotationSpeed": 0.0020, "orbitSpeed": 0.0102, "id_planet": 7, "sizeOriginal": 2.2, "positionOriginal": 201720, "rotationSpeedOriginal": 1.44, "orbitSpeedOriginal": 103.08, "description": "S/2004 S 24 is a prograde irregular moon with a distant and inclined orbit. It was discovered during the Cassini spacecraft's mission to Saturn.", "history": "It was discovered by the Cassini Imaging Science Team in 2004."},
    {"name": "S/2004 S 28", "extendsPlanet": "Saturn", "size": 0.2, "position": 86, "rotationSpeed": 0.0020, "orbitSpeed": 0.0103, "id_planet": 7, "sizeOriginal": 2.2, "positionOriginal": 199110, "rotationSpeedOriginal": 1.44, "orbitSpeedOriginal": 104.28, "description": "S/2004 S 28 is a prograde irregular moon with a distant and inclined orbit. It was discovered during the Cassini spacecraft's mission to Saturn.", "history": "It was discovered by the Cassini Imaging Science Team in 2004."},
    {"name": "S/2004 S 36", "extendsPlanet": "Saturn", "size": 0.2, "position": 87, "rotationSpeed": 0.0019, "orbitSpeed": 0.0104, "id_planet": 7, "sizeOriginal": 2.2, "positionOriginal": 196970, "rotationSpeedOriginal": 1.368, "orbitSpeedOriginal": 105.48, "description": "S/2004 S 36 is a prograde irregular moon with a distant and inclined orbit. It was discovered during the Cassini spacecraft's mission to Saturn.", "history": "It was discovered by the Cassini Imaging Science Team in 2004."},
    {"name": "S/2004 S 37", "extendsPlanet": "Saturn", "size": 0.2, "position": 88, "rotationSpeed": 0.0019, "orbitSpeed": 0.0105, "id_planet": 7, "sizeOriginal": 2.2, "positionOriginal": 195580, "rotationSpeedOriginal": 1.368, "orbitSpeedOriginal": 106.68, "description": "S/2004 S 37 is a prograde irregular moon with a distant and inclined orbit. It was discovered during the Cassini spacecraft's mission to Saturn.", "history": "It was discovered by the Cassini Imaging Science Team in 2004."},
    {"name": "S/2004 S 39", "extendsPlanet": "Saturn", "size": 0.2, "position": 89, "rotationSpeed": 0.0019, "orbitSpeed": 0.0106, "id_planet": 7, "sizeOriginal": 2.2, "positionOriginal": 195700, "rotationSpeedOriginal": 1.368, "orbitSpeedOriginal": 107.88, "description": "S/2004 S 39 is a prograde irregular moon with a distant and inclined orbit. It was discovered during the Cassini spacecraft's mission to Saturn.", "history": "It was discovered by the Cassini Imaging Science Team in 2004."},
    {"name": "S/2006 S 1", "extendsPlanet": "Saturn", "size": 0.2, "position": 90, "rotationSpeed": 0.0018, "orbitSpeed": 0.0107, "id_planet": 7, "sizeOriginal": 2.2, "positionOriginal": 206820, "rotationSpeedOriginal": 1.296, "orbitSpeedOriginal": 108.08, "description": "S/2006 S 1 is a prograde irregular moon with a distant and inclined orbit. It was discovered during the Cassini spacecraft's mission to Saturn.", "history": "It was discovered by the Cassini Imaging Science Team in 2006."},
    {"name": "S/2006 S 3", "extendsPlanet": "Saturn", "size": 0.2, "position": 91, "rotationSpeed": 0.0018, "orbitSpeed": 0.0108, "id_planet": 7, "sizeOriginal": 2.2, "positionOriginal": 201460, "rotationSpeedOriginal": 1.296, "orbitSpeedOriginal": 109.28, "description": "S/2006 S 3 is a prograde irregular moon with a distant and inclined orbit. It was discovered during the Cassini spacecraft's mission to Saturn.", "history": "It was discovered by the Cassini Imaging Science Team in 2006."},
    {"name": "S/2007 S 2", "extendsPlanet": "Saturn", "size": 0.2, "position": 92, "rotationSpeed": 0.0018, "orbitSpeed": 0.0109, "id_planet": 7, "sizeOriginal": 2.2, "positionOriginal": 199950, "rotationSpeedOriginal": 1.296, "orbitSpeedOriginal": 110.48, "description": "S/2007 S 2 is a prograde irregular moon with a distant and inclined orbit. It was discovered during the Cassini spacecraft's mission to Saturn.", "history": "It was discovered by the Cassini Imaging Science Team in 2007."},
    {"name": "S/2007 S 3", "extendsPlanet": "Saturn", "size": 0.2, "position": 93, "rotationSpeed": 0.0018, "orbitSpeed": 0.0110, "id_planet": 7, "sizeOriginal": 2.2, "positionOriginal": 195850, "rotationSpeedOriginal": 1.296, "orbitSpeedOriginal": 111.68, "description": "S/2007 S 3 is a prograde irregular moon with a distant and inclined orbit. It was discovered during the Cassini spacecraft's mission to Saturn.", "history": "It was discovered by the Cassini Imaging Science Team in 2007."},
    {"name": "S/2009 S 1", "extendsPlanet": "Saturn", "size": 0.2, "position": 94, "rotationSpeed": 0.0018, "orbitSpeed": 0.0111, "id_planet": 7, "sizeOriginal": 2.2, "positionOriginal": 197560, "rotationSpeedOriginal": 1.296, "orbitSpeedOriginal": 112.88, "description": "S/2009 S 1 is a prograde irregular moon with a distant and inclined orbit. It was discovered during the Cassini spacecraft's mission to Saturn.", "history": "It was discovered by the Cassini Imaging Science Team in 2009."},
    {"name": "S/2019 S 1", "extendsPlanet": "Saturn", "size": 0.2, "position": 95, "rotationSpeed": 0.0018, "orbitSpeed": 0.0112, "id_planet": 7, "sizeOriginal": 2.2, "positionOriginal": 199740, "rotationSpeedOriginal": 1.296, "orbitSpeedOriginal": 114.08, "description": "S/2019 S 1 is a prograde irregular moon with a distant and inclined orbit. It was discovered during the Cassini spacecraft's mission to Saturn.", "history": "It was discovered by the Cassini Imaging Science Team in 2019."},


    # Uranus' moons
    { "name": "Miranda", "extendsPlanet": "Uranus", "size": 1.3, "position": 14, "rotationSpeed": 0.039, "orbitSpeed": 0.007, "id_planet": 8, "sizeOriginal": 471.6, "positionOriginal": 129390, "rotationSpeedOriginal": 1.413, "orbitSpeedOriginal": 4.68,
      "description": "Miranda is known for its unique and varied terrain.", "history": "It was discovered by Gerard P. Kuiper in 1948." },
    { "name": "Ariel", "extendsPlanet": "Uranus", "size": 2.1, "position": 18, "rotationSpeed": 0.034, "orbitSpeed": 0.006, "id_planet": 8, "sizeOriginal": 1158.4, "positionOriginal": 190900, "rotationSpeedOriginal": 2.52, "orbitSpeedOriginal": 6.48,
      "description": "Ariel is one of Uranus' five major moons and has a relatively young and bright surface.", "history": "It was discovered by William Lassell in 1851." },
    { "name": "Oberon", "extendsPlanet": "Uranus", "size": 2.4, "position": 23, "rotationSpeed": 0.026, "orbitSpeed": 0.005, "id_planet": 8, "sizeOriginal": 1522.8, "positionOriginal": 583520, "rotationSpeedOriginal": 13.463, "orbitSpeedOriginal": 7.2,
      "description": "Oberon is the outermost major moon of Uranus and has a heavily cratered surface.", "history": "It was discovered by William Herschel in 1787." },
    { "name": "Titania", "extendsPlanet": "Uranus", "size": 2.5, "position": 30, "rotationSpeed": 0.023, "orbitSpeed": 0.004, "id_planet": 8, "sizeOriginal": 1575.8, "positionOriginal": 436300, "rotationSpeedOriginal": 8.706, "orbitSpeedOriginal": 5.16,
      "description": "Titania is the largest of Uranus' moons and has a relatively bland and cratered surface.", "history": "It was discovered by William Herschel in 1787." },
    { "name": "Umbriel", "extendsPlanet": "Uranus", "size": 2.0, "position": 37, "rotationSpeed": 0.031, "orbitSpeed": 0.005, "id_planet": 8, "sizeOriginal": 1169.4, "positionOriginal": 265970, "rotationSpeedOriginal": 4.144, "orbitSpeedOriginal": 4.68,
      "description": "Umbriel is known for its heavily cratered surface and dark patches.", "history": "It was discovered by William Lassell in 1851." },
    {"name": "Cordelia", "extendsPlanet": "Uranus", "size": 0.03, "position": 40, "rotationSpeed": 0.084, "orbitSpeed": 0.017, "id_planet": 8, "sizeOriginal": 40.4, "positionOriginal": 49800, "rotationSpeedOriginal": 0.336, "orbitSpeedOriginal": 27.52, "description": "Cordelia is one of Uranus' inner moons and is known for its role in the Cordelia-Ophelia ring arcs.", "history": "It was discovered by Voyager 2 in 1986."},
    {"name": "Ophelia", "extendsPlanet": "Uranus", "size": 0.04, "position": 52, "rotationSpeed": 0.084, "orbitSpeed": 0.018, "id_planet": 8, "sizeOriginal": 43.4, "positionOriginal": 53790, "rotationSpeedOriginal": 0.336, "orbitSpeedOriginal": 32.36, "description": "¡Ophelia is one of Uranus' inner moons and is known for its role in the Cordelia-Ophelia ring arcs.", "history": "It was discovered by Voyager 2 in 1986."},
    {"name": "Bianca", "extendsPlanet": "Uranus", "size": 0.04, "position": 63, "rotationSpeed": 0.098, "orbitSpeed": 0.019, "id_planet": 8, "sizeOriginal": 51.4, "positionOriginal": 59200, "rotationSpeedOriginal": 0.392, "orbitSpeedOriginal": 44.8, "description": "Bianca is one of Uranus' inner moons and is known for its role in the Cordelia-Ophelia ring arcs.", "history": "It was discovered by Voyager 2 in 1986."},
    {"name": "Cressida", "extendsPlanet": "Uranus", "size": 0.04, "position": 74, "rotationSpeed": 0.106, "orbitSpeed": 0.020, "id_planet": 8, "sizeOriginal": 51.4, "positionOriginal": 61780, "rotationSpeedOriginal": 0.424, "orbitSpeedOriginal": 47.92, "description": "Cressida is one of Uranus' inner moons and is known for its role in the Cressida-Desdemona ring arcs.", "history": "It was discovered by Voyager 2 in 1986."},
    {"name": "Desdemona", "extendsPlanet": "Uranus", "size": 0.04, "position": 85, "rotationSpeed": 0.110, "orbitSpeed": 0.021, "id_planet": 8, "sizeOriginal": 53.4, "positionOriginal": 62760, "rotationSpeedOriginal": 0.440, "orbitSpeedOriginal": 50.96, "description": "Desdemona is one of Uranus' inner moons and is known for its role in the Cressida-Desdemona ring arcs.", "history": "It was discovered by Voyager 2 in 1986."},
    {"name": "Juliet", "extendsPlanet": "Uranus", "size": 0.06, "position": 96, "rotationSpeed": 0.106, "orbitSpeed": 0.022, "id_planet": 8, "sizeOriginal": 64.2, "positionOriginal": 64350, "rotationSpeedOriginal": 0.424, "orbitSpeedOriginal": 54.56, "description": "Juliet is one of Uranus' inner moons and is known for its role in the Cressida-Desdemona ring arcs.", "history": "It was discovered by Voyager 2 in 1986."},
    {"name": "Portia", "extendsPlanet": "Uranus", "size": 0.10, "position": 107, "rotationSpeed": 0.100, "orbitSpeed": 0.023, "id_planet": 8, "sizeOriginal": 135.2, "positionOriginal": 66100, "rotationSpeedOriginal": 0.400, "orbitSpeedOriginal": 55.16, "description": "Portia is one of Uranus' inner moons and is known for its role in the Portia-Mab ring arcs.", "history": "It was discovered by Voyager 2 in 1986."},
    {"name": "Rosalind", "extendsPlanet": "Uranus", "size": 0.08, "position": 118, "rotationSpeed": 0.099, "orbitSpeed": 0.024, "id_planet": 8, "sizeOriginal": 108.2, "positionOriginal": 69940, "rotationSpeedOriginal": 0.396, "orbitSpeedOriginal": 56.76, "description": "Rosalind is one of Uranus' inner moons and is known for its role in the Portia-Mab ring arcs.", "history": "It was discovered by Voyager 2 in 1986."},
    {"name": "Belinda", "extendsPlanet": "Uranus", "size": 0.06, "position": 129, "rotationSpeed": 0.098, "orbitSpeed": 0.025, "id_planet": 8, "sizeOriginal": 81.4, "positionOriginal": 75350, "rotationSpeedOriginal": 0.392, "orbitSpeedOriginal": 58.36, "description": "Belinda is one of Uranus' inner moons and is known for its role in the Portia-Mab ring arcs.", "history": "It was discovered by Voyager 2 in 1986."},
    {"name": "Puck", "extendsPlanet": "Uranus", "size": 0.08, "position": 135, "rotationSpeed": 0.119, "orbitSpeed": 0.026, "id_planet": 8, "sizeOriginal": 101.6, "positionOriginal": 86010, "rotationSpeedOriginal": 0.476, "orbitSpeedOriginal": 59.96, "description": "Puck is one of Uranus' inner moons and is one of the largest inner moons.", "history": "It was discovered by Voyager 2 in 1985."},
    {"name": "Caliban", "extendsPlanet": "Uranus", "size": 0.12, "position": 141, "rotationSpeed": 0.124, "orbitSpeed": 0.027, "id_planet": 8, "sizeOriginal": 161.2, "positionOriginal": 72390, "rotationSpeedOriginal": 0.496, "orbitSpeedOriginal": 60.56, "description": "Caliban is one of Uranus' irregular moons with a distant and inclined orbit.", "history": "It was discovered by Brett J. Gladman, Phil D. Nicholson, Joseph A. Burns, and John J. Kavelaars in 1997."},
    {"name": "Sycorax", "extendsPlanet": "Uranus", "size": 0.16, "position": 152, "rotationSpeed": 0.125, "orbitSpeed": 0.028, "id_planet": 8, "sizeOriginal": 214.2, "positionOriginal": 122190, "rotationSpeedOriginal": 0.5, "orbitSpeedOriginal": 61.16, "description": "Sycorax is one of Uranus' irregular moons with a distant and inclined orbit.", "history": "It was discovered by Philip D. Nicholson, Brett J. Gladman, Joseph A. Burns, and John J. Kavelaars in 1997."},
    {"name": "Prospero", "extendsPlanet": "Uranus", "size": 0.10, "position": 163, "rotationSpeed": 0.104, "orbitSpeed": 0.029, "id_planet": 8, "sizeOriginal": 134.2, "positionOriginal": 77400, "rotationSpeedOriginal": 0.416, "orbitSpeedOriginal": 61.76, "description": "Prospero is one of Uranus' irregular moons with a distant and inclined orbit.", "history": "It was discovered by Brett J. Gladman, Phil D. Nicholson, Joseph A. Burns, and John J. Kavelaars in 1999."},
    {"name": "Setebos", "extendsPlanet": "Uranus", "size": 0.10, "position": 169, "rotationSpeed": 0.102, "orbitSpeed": 0.030, "id_planet": 8, "sizeOriginal": 129.2, "positionOriginal": 83980, "rotationSpeedOriginal": 0.408, "orbitSpeedOriginal": 62.36, "description": "Setebos is one of Uranus' irregular moons with a distant and inclined orbit.", "history": "It was discovered by Brett J. Gladman, Phil D. Nicholson, Joseph A. Burns, and John J. Kavelaars in 1999."},
    {"name": "Stephano", "extendsPlanet": "Uranus", "size": 0.06, "position": 175, "rotationSpeed": 0.091, "orbitSpeed": 0.031, "id_planet": 8, "sizeOriginal": 81.6, "positionOriginal": 79420, "rotationSpeedOriginal": 0.364, "orbitSpeedOriginal": 62.96, "description": "Stephano is one of Uranus' irregular moons with a distant and inclined orbit.", "history": "It was discovered by Brett J. Gladman, Philip D. Nicholson, and Joseph A. Burns in 1999."},
    {"name": "Trinculo", "extendsPlanet": "Uranus", "size": 0.06, "position": 180, "rotationSpeed": 0.086, "orbitSpeed": 0.032, "id_planet": 8, "sizeOriginal": 76.6, "positionOriginal": 85700, "rotationSpeedOriginal": 0.344, "orbitSpeedOriginal": 63.56, "description": "Trinculo is one of Uranus' irregular moons with a distant and inclined orbit.", "history": "It was discovered by Matthew J. Holman, John J. Kavelaars, Dan Milisavljevic, and Brett J. Gladman in 2001."},
    {"name": "Francisco", "extendsPlanet": "Uranus", "size": 0.06, "position": 185, "rotationSpeed": 0.090, "orbitSpeed": 0.033, "id_planet": 8, "sizeOriginal": 76.6, "positionOriginal": 86250, "rotationSpeedOriginal": 0.36, "orbitSpeedOriginal": 64.16, "description": "Francisco is one of Uranus' irregular moons with a distant and inclined orbit.", "history": "It was discovered by Matthew J. Holman, John J. Kavelaars, Dan Milisavljevic, and Brett J. Gladman in 2001."},
    {"name": "Margaret", "extendsPlanet": "Uranus", "size": 0.06, "position": 190, "rotationSpeed": 0.087, "orbitSpeed": 0.034, "id_planet": 8, "sizeOriginal": 81.6, "positionOriginal": 87580, "rotationSpeedOriginal": 0.348, "orbitSpeedOriginal": 64.76, "description": "Margaret is one of Uranus' irregular moons with a distant and inclined orbit.", "history": "It was discovered by Matthew J. Holman, John J. Kavelaars, Dan Milisavljevic, and Brett J. Gladman in 2003."},
    {"name": "Ferdinand", "extendsPlanet": "Uranus", "size": 0.04, "position": 195, "rotationSpeed": 0.094, "orbitSpeed": 0.035, "id_planet": 8, "sizeOriginal": 53.6, "positionOriginal": 82290, "rotationSpeedOriginal": 0.376, "orbitSpeedOriginal": 65.36, "description": "Ferdinand is one of Uranus' small inner moons.", "history": "It was discovered by Matthew J. Holman, John J. Kavelaars, and Dan Milisavljevic in 2001."},
    {"name": "Perdita", "extendsPlanet": "Uranus", "size": 0.06, "position": 200, "rotationSpeed": 0.094, "orbitSpeed": 0.036, "id_planet": 8, "sizeOriginal": 76.6, "positionOriginal": 76490, "rotationSpeedOriginal": 0.376, "orbitSpeedOriginal": 65.96, "description": "Perdita is one of Uranus' small inner moons.", "history": "It was discovered by Stephen P. Synnott and Voyager 2 in 1986."},
    {"name": "Mab", "extendsPlanet": "Uranus", "size": 0.02, "position": 205, "rotationSpeed": 0.119, "orbitSpeed": 0.037, "id_planet": 8, "sizeOriginal": 27.6, "positionOriginal": 97700, "rotationSpeedOriginal": 0.476, "orbitSpeedOriginal": 66.56, "description": "Mab is one of Uranus' small inner moons.", "history": "It was discovered by Mark R. Showalter and Jack J. Lissauer in 2003."},
    {"name": "Cupid", "extendsPlanet": "Uranus", "size": 0.02, "position": 210, "rotationSpeed": 0.120, "orbitSpeed": 0.038, "id_planet": 8, "sizeOriginal": 27.6, "positionOriginal": 74300, "rotationSpeedOriginal": 0.480, "orbitSpeedOriginal": 67.16, "description": "Cupid is one of Uranus' small inner moons.", "history": "It was discovered by Mark R. Showalter and Jack J. Lissauer in 2003."},



    # Neptune's moons
    { "name": "Triton", "extendsPlanet": "Neptune", "size": 5, "position": 42, "rotationSpeed": 0.023, "orbitSpeed": 0.01, "id_planet": 9, "sizeOriginal": 2706.8, "positionOriginal": 354800, "rotationSpeedOriginal": -5.877, "orbitSpeedOriginal": 76.32,
      "description": "Triton is the largest moon of Neptune and is unique for its retrograde orbit.", "history": "It was discovered by William Lassell in 1846, just 17 days after Neptune was discovered." },
    { "name": "Nereida", "extendsPlanet": "Neptune", "size": 2, "position": 53, "rotationSpeed": 0.027, "orbitSpeed": 0.0067, "id_planet": 9, "sizeOriginal": 170.6, "positionOriginal": 5513810, "rotationSpeedOriginal": 360.136, "orbitSpeedOriginal": 5.4,
      "description": "Nereida is a small irregular moon of Neptune.", "history": "It was discovered in 1949 by Gerard P. Kuiper." },
    { "name": "Proteus", "extendsPlanet": "Neptune", "size": 4, "position": 32, "rotationSpeed": 0.032, "orbitSpeed": 0.001, "id_planet": 9, "sizeOriginal": 420.2, "positionOriginal": 117646, "rotationSpeedOriginal": -176.52, "orbitSpeedOriginal": 1.12,
    "description": "Proteus is one of Neptune's largest moons and has a unique elongated shape.", "history": "It was discovered in 1989 by the Voyager 2 spacecraft." },
    { "name": "Galatea", "extendsPlanet": "Neptune", "size": 2, "position": 9, "rotationSpeed": 0.025, "orbitSpeed": 0.006, "id_planet": 9, "sizeOriginal": 174.8, "positionOriginal": 61953, "rotationSpeedOriginal": 360.48, "orbitSpeedOriginal": 4.5,
      "description": "Galatea is a small moon of Neptune known for its relatively high reflectivity.", "history": "It was discovered in 1989 by the Voyager 2 spacecraft." },
    { "name": "Larissa", "extendsPlanet": "Neptune", "size": 2.5, "position": 20, "rotationSpeed": 0.024, "orbitSpeed": 0.0005, "id_planet": 9, "sizeOriginal": 194, "positionOriginal": 73548, "rotationSpeedOriginal": 187.68, "orbitSpeedOriginal": 0.554,
      "description": "Larissa is one of Neptune's inner moons and was discovered during the Voyager 2 flyby.", "history": "It was discovered in 1981 by Harold J. Reitsema et al." },
    {"name": "Naiad", "extendsPlanet": "Neptune", "size": 0.04, "position": 25, "rotationSpeed": 0.294, "orbitSpeed": 0.039, "id_planet": 9, "sizeOriginal": 58.2, "positionOriginal": 48280, "rotationSpeedOriginal": 1.176, "orbitSpeedOriginal": 72.40, "description": "Naiad is one of Neptune's inner moons and is part of the ring system.", "history": "It was discovered by Voyager 2 in 1989."},
    {"name": "Thalassa", "extendsPlanet": "Neptune", "size": 0.06, "position": 26, "rotationSpeed": 0.297, "orbitSpeed": 0.040, "id_planet": 9, "sizeOriginal": 76.4, "positionOriginal": 50074, "rotationSpeedOriginal": 1.188, "orbitSpeedOriginal": 73.00, "description": "Thalassa is one of Neptune's inner moons and is part of the ring system.", "history": "It was discovered by Voyager 2 in 1989."},
    {"name": "Despina", "extendsPlanet": "Neptune", "size": 0.10, "position": 27, "rotationSpeed": 0.282, "orbitSpeed": 0.041, "id_planet": 9, "sizeOriginal": 144.8, "positionOriginal": 52526, "rotationSpeedOriginal": 1.128, "orbitSpeedOriginal": 73.60, "description": "Despina is one of Neptune's inner moons and is part of the ring system.", "history": "It was discovered by Voyager 2 in 1989."},
    {"name": "Halimede", "extendsPlanet": "Neptune", "size": 0.04, "position": 29, "rotationSpeed": 0.297, "orbitSpeed": 0.043, "id_planet": 9, "sizeOriginal": 63.2, "positionOriginal": 10528340, "rotationSpeedOriginal": 1.188, "orbitSpeedOriginal": 1878.00, "description": "Halimede is one of Neptune's irregular moons with a distant and inclined orbit.", "history": "It was discovered by Brett J. Gladman, John J. Kavelaars, Jean-Marc Petit, and Hans Scholl in 2002."},
    {"name": "Psamathe", "extendsPlanet": "Neptune", "size": 0.06, "position": 30, "rotationSpeed": 0.292, "orbitSpeed": 0.044, "id_planet": 9, "sizeOriginal": 77.2, "positionOriginal": 4688314, "rotationSpeedOriginal": 1.168, "orbitSpeedOriginal": 2225.00, "description": "Psamathe is one of Neptune's irregular moons with a distant and inclined orbit.", "history": "It was discovered by Scott S. Sheppard and David C. Jewitt in 2003."},
    {"name": "Sao", "extendsPlanet": "Neptune", "size": 0.04, "position": 31, "rotationSpeed": 0.299, "orbitSpeed": 0.045, "id_planet": 9, "sizeOriginal": 53.2, "positionOriginal": 22614000, "rotationSpeedOriginal": 1.196, "orbitSpeedOriginal": 2914.00, "description": "Sao is one of Neptune's irregular moons with a distant and inclined orbit.", "history": "It was discovered by Matthew J. Holman, John J. Kavelaars, Tommy Grav, Wesley C. Fraser, and Dan Milisavljevic in 2002."},
    {"name": "Laomedeia", "extendsPlanet": "Neptune", "size": 0.06, "position": 32, "rotationSpeed": 0.286, "orbitSpeed": 0.046, "id_planet": 9, "sizeOriginal": 81.2, "positionOriginal": 23570400, "rotationSpeedOriginal": 1.144, "orbitSpeedOriginal": 3128.00, "description": "Laomedeia is one of Neptune's irregular moons with a distant and inclined orbit.", "history": "It was discovered by Matthew J. Holman, John J. Kavelaars, Tommy Grav, Wesley C. Fraser, and Dan Milisavljevic in 2002."},
    {"name": "Neso", "extendsPlanet": "Neptune", "size": 0.08, "position": 33, "rotationSpeed": 0.280, "orbitSpeed": 0.047, "id_planet": 9, "sizeOriginal": 108.4, "positionOriginal": 49723000, "rotationSpeedOriginal": 1.120, "orbitSpeedOriginal": 3723.00, "description": "Neso is one of Neptune's irregular moons with a distant and highly inclined orbit.", "history": "It was discovered by Matthew J. Holman, John J. Kavelaars, Tommy Grav, Wesley C. Fraser, and Dan Milisavljevic in 2002."},
    {"name": "Hippocamp", "extendsPlanet": "Neptune", "size": 0.04, "position": 34, "rotationSpeed": 0.301, "orbitSpeed": 0.048, "id_planet": 9, "sizeOriginal": 58.2, "positionOriginal": 10529132, "rotationSpeedOriginal": 1.204, "orbitSpeedOriginal": 3188.00, "description": "Hippocamp is one of Neptune's smallest moons and orbits within Proteus' orbit.", "history": "It was discovered by Mark R. Showalter and collaborators using Hubble Space Telescope data in 2013."}


]
  

# Execute a command: this creates a new table
cur.execute('DROP TABLE IF EXISTS moonsData CASCADE;')
cur.execute('CREATE TABLE moonsData ('
            'id_moon SERIAL PRIMARY KEY,'
            'name VARCHAR(32) NOT NULL,'
            'extendsPlanet VARCHAR(32) NOT NULL,'
            'size NUMERIC(5, 2) NOT NULL,'
            'position SMALLINT NOT NULL,'
            'rotationSpeed NUMERIC(5, 4) NOT NULL,'
            'orbitSpeed NUMERIC(4, 3) NOT NULL,'
            'id_planet SMALLINT,'
            'sizeOriginal NUMERIC(7, 2),'
            'positionOriginal INTEGER,'
            'rotationSpeedOriginal NUMERIC(8, 5),'
            'orbitSpeedOriginal NUMERIC(9, 5),'
            'description TEXT,'
            'history TEXT);')


# Execute a command: this creates a new table
cur.execute('DROP TABLE IF EXISTS planetsData;')
cur.execute('CREATE TABLE planetsData (id_planet SERIAL PRIMARY KEY,'
    ' name VARCHAR(32) NOT NULL,'
    ' size SMALLINT NOT NULL,'
    ' position SMALLINT NOT NULL,'
    ' rotation_speed NUMERIC(5, 3) NOT NULL,'
    ' orbit_speed NUMERIC(5, 4) NOT NULL,'
    ' num_moons SMALLINT NOT NULL,'
    ' inner_radius SMALLINT NULL,'
    ' outer_radius SMALLINT NULL,'
    ' description TEXT NOT NULL,'
    ' history TEXT NOT NULL,'
    ' size_original INT NOT NULL,'
    ' position_original NUMERIC(8, 2) NOT NULL,'
    ' rotation_speed_original NUMERIC(8, 5) NOT NULL,'
    ' orbit_speed_original NUMERIC(8, 6) NOT NULL);'
)


# SQL command to insert data into the moonsData table
insert_moon_query = """
    INSERT INTO moonsData (name, extendsPlanet, id_planet, size, position, rotationSpeed, orbitSpeed, 
                          sizeOriginal, positionOriginal, rotationSpeedOriginal, orbitSpeedOriginal,
                          description, history)
    VALUES (%(name)s, %(extends_planet)s, %(id_planet)s, %(size)s, %(position)s, %(rotationSpeed)s, %(orbitSpeed)s,
            %(sizeOriginal)s, %(positionOriginal)s, %(rotationSpeedOriginal)s, %(orbitSpeedOriginal)s,
            %(description)s, %(history)s);
"""

# Loop through the moonsData array and insert each moon's data into the table
for moon in moonsData:
    moon_data = {
        'name': moon['name'],
        'extends_planet': moon['extendsPlanet'],
        'size': moon['size'],
        'position': moon['position'],
        'rotationSpeed': moon['rotationSpeed'],
        'orbitSpeed': moon['orbitSpeed'],
        'id_planet': moon['id_planet'],
        'sizeOriginal': moon['sizeOriginal'],
        'positionOriginal': moon['positionOriginal'],
        'rotationSpeedOriginal': moon['rotationSpeedOriginal'],
        'orbitSpeedOriginal': moon['orbitSpeedOriginal'],
        'description': moon['description'],
        'history': moon['history']
    }
    cur.execute(insert_moon_query, moon_data)


# Commit the changes to the database
conn.commit()

# SQL command to insert data into the planetsData table
insert_query = """
    INSERT INTO planetsData (name, size, position, rotation_speed, orbit_speed, num_moons,
    inner_radius, outer_radius, description, history, size_original, position_original, 
    rotation_speed_original, orbit_speed_original)

    VALUES (%(name)s, %(size)s, %(position)s, %(rotationSpeed)s, %(orbitSpeed)s, %(moons)s,
     %(innerRadius)s, %(outerRadius)s, %(description)s, %(history)s, %(sizeOriginal)s, %(positionOriginal)s,
     %(rotationSpeedOriginal)s, %(orbitSpeedOriginal)s)
"""

# Loop through the planetsData array and insert each planet's data into the table
for planet in planetsData:
    planet_data = {
        'name': planet['name'],
        'size': planet['size'],
        'position': planet['position'],
        'rotationSpeed': planet['rotationSpeed'],
        'orbitSpeed': planet['orbitSpeed'],
        'moons': planet['moons'],
        'innerRadius': planet.get('innerRadius', None),
        'outerRadius': planet.get('outerRadius', None),
        'description': planet['description'],
        'history': planet['history'],
        'sizeOriginal': planet['sizeOriginal'],
        'positionOriginal': planet['positionOriginal'],
        'rotationSpeedOriginal': planet['rotationSpeedOriginal'],
        'orbitSpeedOriginal': planet['orbitSpeedOriginal']
    }
    cur.execute(insert_query, planet_data)


# Commit the changes to the database
conn.commit()

cur.close()
conn.close()